#https://docs.docker.com/build/buildkit/configure/
debug = true
[registry."docker.io"]
mirrors = ["docker-registry-proxy.corp.amdocs.com"]
[registry."illin5638.corp.amdocs.com:5002"]
http = true
insecure = true
[registry."registry:6000"]
http = true
insecure = true
[registry."illin4261.corp.amdocs.com:28090"]
http = true
insecure = true
[registry."docker-registry-proxy.corp.amdocs.com"]
http = true
insecure = true
[worker.oci]
enabled = true
# platforms is manually configure platforms, detected automatically if unset.
platforms = [ "linux/amd64", "linux/arm64"]
