---
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-executor-config
  namespace: kagent-system
data:
  config.yaml: |
    temporal:
      host_port: "temporal-frontend.temporal:7233"
      namespace: "default"
      task_queue: "agent-execution-queue"

    executor:
      max_concurrent_workflows: 100
      max_concurrent_activities: 100
      default_timeout: 5m
      max_iterations: 10
      require_approval: false

    llm:
      providers:
        - name: anthropic
          api_key_env: "ANTHROPIC_API_KEY"
        - name: openai
          api_key_env: "OPENAI_API_KEY"

    server:
      host: "0.0.0.0"
      port: 8080

    a2a:
      enabled: true

---
apiVersion: v1
kind: Secret
metadata:
  name: temporal-executor-secrets
  namespace: kagent-system
type: Opaque
stringData:
  ANTHROPIC_API_KEY: ""  # Set this via kubectl or external secrets
  OPENAI_API_KEY: ""     # Set this via kubectl or external secrets

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-executor
  namespace: kagent-system
  labels:
    app: temporal-executor
    component: executor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: temporal-executor
  template:
    metadata:
      labels:
        app: temporal-executor
        component: executor
    spec:
      containers:
      - name: temporal-executor
        image: kagent/temporal-executor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: temporal-executor-secrets
              key: ANTHROPIC_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: temporal-executor-secrets
              key: OPENAI_API_KEY
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: temporal-executor-config

---
apiVersion: v1
kind: Service
metadata:
  name: temporal-executor
  namespace: kagent-system
  labels:
    app: temporal-executor
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: temporal-executor

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: temporal-executor
  namespace: kagent-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: temporal-executor
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
