apiVersion: app.amdocs.com/v1beta1
kind: Microservice
metadata:
  name: dryruntool
  namespace: kagent
spec:
  component: dryruntool
  containerName: dryruntool
  domain: dryruntool
  instance: dryruntool
  maxReplicas: 1
  minReplicas: 1
  template:
    spec:
      containers:
      - image: dryruntool:v2
        imagePullPolicy: IfNotPresent
        name: dryruntool
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /sse
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
  version: 1.0.0
