[install]

# equivalent to `--production` flag
production = true

# whether to install devDependencies
dev = true

# whether to install optionalDependencies
optional = true

# whether to install peerDependencies
peer = true

# equivalent to `--save-text-lockfile` flag
saveTextLockfile = true

# equivalent to `--frozen-lockfile` flag frozenLockfile = false

#registry = "http://docker-registry-proxy.corp.amdocs.com:8081/repository/npm-external/"

registry = "http://docker-registry-proxy.corp.amdocs.com/repository/npm-amdocs/"

noproxy = "localhost,127.0.0.1,docker-registry-proxy.corp.amdocs.com"
