[install]

registry = "http://docker-registry-proxy.corp.amdocs.com:8081/repository/npm-external/"

proxy = "http://10.232.233.70:8080"

no_proxy = "localhost,127.0.0.1,corp.amdocs.com"

# equivalent to `--production` flag
production = true

# whether to install devDependencies
dev = true

# whether to install optionalDependencies
optional = true

# whether to install peerDependencies
peer = false

# equivalent to `--save-text-lockfile` flag
saveTextLockfile = false

# equivalent to `--frozen-lockfile` flag
frozenLockfile = true