[install]

registry = "http://127.0.0.1:4873"

noproxy = "127.0.0.1,localhost"

logLevel = "debug"

telemetry = false

production = true

dev = true

optional = true

peer = false

saveTextLockfile = false

frozenLockfile = true

[test]
coverage = false