# Default values for kagent
replicaCount: 1

global:
  tag: ""

# https://kagent.dev/docs/getting-started/configuring-providers
providers:
  default: azureOpenAI
  openAI:
    provider: OpenAI
    model: "gpt-4.1-mini"
    apiKeySecretRef: kagent-openai
    apiKeySecretKey: OPENAI_API_KEY
    apiKey: ""
  ollama:
    provider: Ollama
    model: "llama3.2"
    config:
      host: host.lima.internal:11434
  anthropic:
    provider: Anthropic
    model: "claude-3-sonnet-20240229"
    apiKeySecretRef: kagent-anthropic
    apiKeySecretKey: ANTHROPIC_API_KEY
    apiKey: ""
  azureOpenAI:
    provider: AzureOpenAI
    model: "gpt-4.1-mini"
    apiKeySecretRef: kagent-azure-openai
    apiKeySecretKey: AZUREOPENAI_API_KEY
    apiKey: ""
    defaultHeaders:
      username: "dmitriyr"
      application: "kagent"
    config:
      apiVersion: "2024-10-21"
      azureAdToken: ""
      azureDeployment: "gpt-4.1-mini"
      azureEndpoint: "https://chat.autox.corp.amdocs.azr/api/v1/proxy"

controller:
  loglevel: "debug"

  # -- Namespaces the controller should watch.
  # If empty, the controller will watch ONLY release namespace.
  # @default -- [] (watches release namespace)
  watchNamespaces: []
  #  - watch-ns-1
  #  - watch-ns-2

  image:
    registry: illin4261.corp.amdocs.com:28090/platform
    repository: kagent/controller
    tag: "" # Will default to global, then Chart version
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env: [] # Additional environment variables for the controller can be added here

app:
  image:
    registry: illin4261.corp.amdocs.com:28090/platform
    repository: kagent/app
    tag: "" # Will default to global, then Chart version
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 2Gi
  env: []
#    - name: https_proxy
#      value: https://192.168.8.1:3128
#    - name: no_proxy
#      value: 0.42.0.0/16,0.42.0.0/16,127.0.0.1,*.corp.amdocs.com,localhost
#    - name: REQUESTS_CA_BUNDLE
#      value: /app/python/amdcerts.pem
#    - name: SSL_CERT_FILE
#      value: /app/python/amdcerts.pem
ui:
  image:
    registry: illin4261.corp.amdocs.com:28090/platform
    repository: kagent/ui
    tag: "" # Will default to global, then Chart version
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  env: [] # Additional environment variables for the ui can be added here

service:
  type: ClusterIP
  ports:
    ui:
      port: 80
      targetPort: 80
    app:
      port: 8081
      targetPort: 8081
    controller:
      port: 8083
      targetPort: 8083

imagePullSecrets:
  - name: amdocs-nexus-pull-secret

nameOverride: ""
fullnameOverride: ""

# -- Override the namespace
# @default -- `.Release.Namespace`
namespaceOverride: ""

podAnnotations:
  sidecar.istio.io/inject: "true"
  #ignore otel outbound traffic
  traffic.sidecar.istio.io/excludeOutboundPorts: "4317,4318,4319,8080,8081,8082,8083"
  sidecar.istio.io/componentLogLevel: "http:debug,client:info,connection:info,conn_handler:info,pool:info"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

otel:
  tracing:
    enabled: true
    exporter:
      otlp:
        endpoint: http://host.lima.internal:4317
        timeout: 10
        insecure: true

k8s-agent:
  enabled: true

kgateway-agent:
  enabled: true

istio-agent:
  enabled: true

promql-agent:
  enabled: true

observability-agent:
  enabled: true
  prometheus:
    url: ""
    username: ""
    password: ""
  grafana:
    url: ""
    username: ""
    password: ""
    apiKey: ""

argo-rollouts-agent:
  enabled: true

helm-agent:
  enabled: true

cilium-crd-agent:
  enabled: false
